Fixed the rounds going up every time a player changes. Now all the pl…
kristjankivikangur/3TARe-2017-Yahtzee pull request #33
Opened 2017-10-10 14:24 UTC by TomyKalm

…ayers are ran before going to the next round

2017-10-11 12:52 UTC, kristjankivikangur commented on src/ee/tthk/impls/game/Game.java
> +        for (int i = 1; i <= 1; i++){
Mittevajalik for tsükkel. Seda läbitakse üks kord.

2017-10-11 12:53 UTC, kristjankivikangur commented on src/ee/tthk/impls/game/Game.java
>              ChangePlayer();
Kas järgmise mängijani ka kunagi jõutakse?
CurrentPlayer++ - on nagu puudu.

2017-10-11 12:55 UTC, kristjankivikangur requested changes
Vaata lisatud kommentaare. Muuda koodi või selgita vastusega kommentaarile.

2017-10-12 08:28 UTC, TomyKalm commented on src/ee/tthk/impls/game/Game.java
>              ChangePlayer();
Mängija vahetamine kutsutakse välja ChangePlayer()

2017-10-13 07:45 UTC, kristjankivikangur approved these changes

2017-10-13 08:27 UTC, merged